### PR TITLE
Update _tst.scss

### PR DESCRIPTION
**Pull request by kacycrider**

### CODE REVIEW

**Comment by kacycrider** [comment]
This is my attempt to follow step 1 from the comment in hexennacht CSS -- copying temple into TST CSS

**Comment by hndrewaall** [comment]
Sorry, this one never showed for me. Cool, so you did do both parts. This is the problem with opening multiple PRs instead of updating a single one: they are hard to keep track of.

**Comment by hndrewaall** [comment]
Why did you close this one?

**Comment by hndrewaall** [comment]
If you reopen this one, we can merge this and the other one and close the first.

**Pull request merged**
