### PR TITLE
Revert map and fix formatter

### PR DESCRIPTION
**Pull request by hndrewaall**
Also drop old adventure

### CODE REVIEW

**Comment by hndrewaall** [comment]
@kacycrider take a quick look at this and see if I reverted anything you wanted to keep? I may have lost some descriptions and/or moved some things around incorrectly. But we can also just merge and see. The map looks coherent at least

**Comment by hndrewaall** [comment]
image

**Comment by hndrewaall** [comment]
@kacycrider we'll also need new images since this config refers to the deleted lupercalia images

**Comment by kacycrider** [comment]
This is perfect thank you!

**Pull request merged**
